#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

sudo apt-get update 
sudo apt-get -y install haproxy

# Configure haproxy
cat << EOF |sudo tee -a /etc/haproxy/haproxy.cfg
listen load_balancer
        bind :80
	mode http
	option httpclose
	option forwardfor
        balance roundrobin
	server 148870-web-01 100.26.226.210 check
	server 148870-web-02 54.84.65.163 check
EOF

# Restart haproxy using init script
sudo /etc/init.d/haproxy restart
