#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
# except for TCP ports 22, 443 and 80.

# Checks the path of ufw which is pre-installed
which ufw

# Checks the status of the ufw
sudo ufw status

sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status
